# Generated by Django 2.0.7 on 2018-10-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(db_index=True, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email',)},
        ),
    ]
